language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install codecov pytest-cov flake8 sphinx sphinx_rtd_theme matplotlib

script:
  - pytest --cov=./
  - flake8
  - sphinx-build -W doc doc_build/

after_success:
  - codecov
